// Generated by CoffeeScript 1.9.2
(function() {
  var immutableHelper;

  immutableHelper = {
    getByPath: function(obj, path) {
      var i, len, res, road, roads;
      if (!path || !path.trim()) {
        return obj;
      }
      roads = path.split('/');
      res = obj;
      for (i = 0, len = roads.length; i < len; i++) {
        road = roads[i];
        res = res.get(road);
      }
      return res;
    },
    setByPath: function(obj, path, val) {
      var k, slashIndex;
      if (!path || !path.trim()) {
        return obj;
      }
      while (path) {
        slashIndex = path.lastIndexOf('/');
        k = path.substring(slashIndex + 1, path.length);
        path = path.substring(0, slashIndex);
        val = this.getByPath(obj, path).set(k, val);
      }
      return val;
    },
    pushByPath: function(obj, path, val) {
      if (!path || !path.trim()) {
        return obj;
      }
      return this.setByPath(obj, path, this.getByPath(obj, path).push(val));
    },
    deleteByPath: function(obj, path) {
      var k, slashIndex;
      if (!path || !path.trim()) {
        return obj;
      }
      slashIndex = path.lastIndexOf('/');
      k = path.substring(slashIndex + 1, path.length);
      path = path.substring(0, slashIndex);
      return this.setByPath(obj, path, this.getByPath(obj, path)["delete"](k));
    },
    findByProperty: function(list, propName, propVal) {
      return list.find(function(item) {
        return item.get(propName) === propVal;
      });
    }
  };

  module.exports = immutableHelper;

}).call(this);

//# sourceMappingURL=index.js.map
